apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/tbalza/kubernetes-cicd' # pending remote repo with local overrides
    targetRevision: 'HEAD'
    path: 'argo-apps/jenkins/charts/jenkins' # Chart v5.1.6, App v2.440.3
    helm:
      valueFiles:
        - "../../values-override.yaml"  # Correct relative path from the chart directory
      parameters:
        - name: "serviceAccount.create"
          value: "true"
        - name: "serviceAccount.name"
          value: "jenkins"
        - name: "serviceAccount.annotations.eks\\amazonaws\\com/role-arn"
          value: "arn:aws:iam::350206045032:role/JenkinsRole"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: jenkins
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true # check , not working, likely permissions as ArgoCD ApplicationSet is able to create the namespace