apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: "https://charts.jenkins.io" # pending remote repo with local overrides
    targetRevision: 5.1.6 # # Chart v5.1.6, App v2.440.3
    chart: jenkins
    helm:
      valueFiles:
        - $values/argo-apps/jenkins/values-override.yaml  # Correct relative path from the chart directory
      parameters:
        - name: "serviceAccount.create"
          value: "true"
        - name: "serviceAccount.name"
          value: "jenkins"
        - name: "serviceAccount.annotations.eks\\amazonaws\\com/role-arn"
          value: "argocd:arn:aws:iam::350206045032:role/JenkinsRole"
  - repoURL: "https://github.com/tbalza/kubernetes-cicd.git"
    targetRevision: HEAD
    ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: jenkins
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
