apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://charts.jenkins.io' # pending remote repo with local overrides
    targetRevision: '5.1.6' # # Chart v5.1.6, App v2.440.3
    chart: jenkins
    helm:
      valueFiles:
        - "argo-apps/jenkins/values-override.yaml"  # Correct relative path from the chart directory
      parameters:
        - name: "serviceAccount.create"
          value: "true"
        - name: "serviceAccount.name"
          value: "jenkins"
        - name: "serviceAccount.annotations.eks\\amazonaws\\com/role-arn"
          value: "argocd:arn:aws:iam::350206045032:role/JenkinsRole"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: jenkins
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true # check if working