apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://charts.jenkins.io'
    targetRevision: '5.1.6'  # Define the Helm chart version here
    chart: jenkins
    helm:
      valueFiles:
        - 'https://raw.githubusercontent.com/tbalza/kubernetes-cicd/main/argo-apps/jenkins/values.yaml'  # Path to the values file
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: jenkins
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
