apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/tbalza/kubernetes-cicd' # pending remote repo with local overrides
    targetRevision: 'HEAD'
    path: 'argo-apps/jenkins/charts/jenkins' # Chart v5.1.6, App v2.440.3
    helm:
      valueFiles:
        - ../../values-override.yaml # Relative path from the chart directory to the values-override file
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: jenkins
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
