controller:
  # Jenkins controller configuration
  adminUser: admin
  adminPassword: pass # It's better to use a secret for this

  service:
    type: ClusterIP
    port: 8080

  # Jenkins plugins
  installPlugins:
    - kubernetes:latest
    - workflow-aggregator:latest
    - git:latest
    - configuration-as-code:latest
    - ansible:latest

  # Jenkins Configuration as Code (JCasC)
  JCasC:
    configScripts:
      welcome-message: |
        jenkins:
          systemMessage: "Welcome to our Jenkins!\nConfigured automatically by Jenkins Configuration as Code plugin\n"

# Add more custom values for Jenkins Helm chart as per your requirements
