apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: jenkins
    repo: https://charts.jenkins.io
    version: 5.1.6  # Chart v5.1.6, App v2.440.3
    releaseName: jenkins
    namespace: jenkins
    includeCRDs: true # check if necessary ( as it should be defined in values.yaml)
    valuesFile: values.yaml

resources:
  - secret-store.yaml # load ECR repo dynamically
  - secret-external.yaml # load ECR repo dynamically

configMapGenerator:
  - name: test-config
    files:
      - jenkins.yaml

generatorOptions:
  disableNameSuffixHash: true # This prevents Kustomize from appending a hash to the ConfigMap name.

patches:
  - path: volume-patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: jenkins
      namespace: jenkins


#  labels:
#    type: generated # Labels the generated ConfigMaps and Secrets as 'generated'.
#  annotations:
#    note: generated # Annotates the generated ConfigMaps and Secrets as 'generated'

#  - name: docker-config # kaniko required config
#    literals:
#      - |
#        config.json=|
#          {
#            "credsStore": "ecr-login"
#          }