apiVersion: v1
kind: Pod
metadata:
 name: kaniko
spec:
 containers:
 - name: jnlp
   workingDir: /home/jenkins
 - name: kaniko
   workingDir: /home/jenkins
   image: gcr.io/kaniko-project/executor:debug
   imagePullPolicy: Always
   command:
   - /busybox/cat
   tty: true
   volumeMounts:
   - name: docker-config
     mountPath: /kaniko/.docker/
   - name: aws-secret
     mountPath: /root/.aws/
 restartPolicy: Never
      volumes:
         - name: docker-config
           configMap:
             name: docker-config
         - name: aws-secret
           secret:
             secretName: aws-secret