apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jenkins-secrets
  namespace: jenkins
spec:
  refreshInterval: "0" # default 1h , should only be refreshed on deploy (?)
  secretStoreRef:
    name: jenkins-secrets # must match `SecretStore` name
    kind: SecretStore
  target:
    name: jenkins-secrets
    creationPolicy: Owner # Owner # Owner managed by ESO
    immutable: true # check
  data:
    - secretKey: ECR_REPO # arbitrary assigned key name, used in Jenkinsfile/Pipeline
      remoteRef:
        key: ecr_repo  # The path to SSM parameter
        conversionStrategy: Default # argocd appset will loop infinitely if not set
        decodingStrategy: None # argocd appset will loop infinitely if not set
        metadataPolicy: None # argocd appset will loop infinitely if not set
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: jenkins-secrets
  namespace: jenkins
spec:
  provider:
    aws:
      service: ParameterStore
      region: us-east-1  # AWS region specific, pending dynamic value
      auth:
        jwt: # requires `sts:AssumeRoleWithWebIdentity` permission (set in tf)
          serviceAccountRef:
            name: jenkins # name of actual serviceAccount (not role)
