apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: jenkins-secrets
spec:
  provider:
    aws:
      service: ParameterStore
      region: us-east-1  # AWS region specific, pending dynamic value
      # optional: assume role before fetching secrets
      role: JenkinsRole
#      auth:
#        jwt:
#          serviceAccountRef:
#            name: jenkins
