apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: jenkins-secrets
  #namespace: jenkins
spec:
  provider:
    aws:
      service: ParameterStore
      region: us-east-1  # AWS region specific, pending dynamic value
      # optional: assume role before fetching secrets
#      role: JenkinsRole # needs to be ARN?
      auth:
        jwt:
          serviceAccountRef:
            name: argocd
