controller:
  image: "jenkins/jenkins"
  tag: "2.332.3"  # Latest non-LTS Jenkins version
  adminUser: "admin"
  adminPassword: "pass"  # Consider using secrets for production
  serviceType: "ClusterIP"
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
  service:
    port: 8080
    targetPort: 8181
  installPlugins:
    - kubernetes:latest
    - workflow-aggregator:latest
    - git:latest
    - configuration-as-code:latest
    - ansible:latest
  JCasC:
    enabled: true
    configScripts:
      welcome-message: |
        jenkins:
          systemMessage: "Welcome to our Jenkins!\nConfigured automatically by Jenkins Configuration as Code plugin\n"

persistence:
  enabled: true
  storageClass: "standard"
  size: "10Gi"
  accessMode: "ReadWriteOnce"

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: "role"
          operator: In
          values:
          - "cicd-node"