controller:
  image: "jenkins/jenkins"
  tag: "2.332.3"  # Specified directly if needed here or dynamically through argoapp-jenkins.yaml
  adminUser: "admin"
  adminPassword: "pass"
  serviceType: "ClusterIP"
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
  service:
    port: 8080
    targetPort: 8181
  installPlugins:
    - kubernetes:latest
    - workflow-aggregator:latest
    - git:latest
    - configuration-as-code:latest
    - ansible:latest
  JCasC:
    enabled: true
    configScripts:
      welcome-message: |
        jenkins:
          systemMessage: "Welcome to our Jenkins!\nConfigured automatically by Jenkins Configuration as Code plugin\n"
persistence:
  enabled: true
  storageClass: "standard"
  size: "10Gi"
  accessMode: "ReadWriteOnce"

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: "role"
          operator: In
          values:
          - "cicd-node"

ingress:
  enabled: true
  className: "alb"
  annotations:
    kubernetes.io/ingress.class: "alb"
    alb.ingress.kubernetes.io/scheme: "internet-facing"
    alb.ingress.kubernetes.io/target-type: "ip"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 8080}]'
    alb.ingress.kubernetes.io/group.name: "argo-cd-cluster"  # Helps manage ALB grouping
    alb.ingress.kubernetes.io/group.order: "1"
  paths:
    - path: "/*"
      pathType: ImplementationSpecific
      backend:
        service:
          name: "jenkins"
          port:
            number: 8080