master:
  image: "jenkins/jenkins"
  tag: "2.289.1-lts"
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

controller:
  adminUser: "admin"  # Base64 encoded 'admin'
  adminPassword: "pass"  # Base64 encoded 'pass'
  service:
    type: ClusterIP
    port: 8080
    targetPort: 8181
  installPlugins:
    - kubernetes:latest
    - workflow-aggregator:latest
    - git:latest
    - configuration-as-code:latest
    - ansible:latest
  JCasC:
    configScripts:
      welcome-message: |
        jenkins:
          systemMessage: "Welcome to our Jenkins!\nConfigured automatically by Jenkins Configuration as Code plugin\n"

persistence:
  enabled: true
  storageClass: "standard"
  size: "10Gi"
  accessMode: "ReadWriteOnce"

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: "role"
          operator: In
          values:
          - "cicd-node"
