apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins
spec:
  template:
    spec:
      containers:
      - name: jenkins
        volumeMounts:
          - name: test-config
            mountPath: /var/jenkins_home/jenkins.yaml
            subPath: jenkins.yaml
            readOnly: true
      volumes:
        - name: volume-checkk
          configMap:
            name: test-config
