apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.controller.service.type }}
  ports:
  - port: {{ .Values.controller.service.port }}
    targetPort: {{ .Values.controller.service.targetPort }}
    protocol: TCP
  selector:
    app: jenkins
