apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: django
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: "django=350206045032.dkr.ecr.us-east-1.amazonaws.com/django-production"
    argocd-image-updater.argoproj.io/django.update-strategy: "latest"
    argocd-image-updater.argoproj.io/django.allow-tags: "regexp:^.*"
spec:
  project: default
  source:
    repoURL: https://github.com/tbalza/kubernetes-cicd.git
    targetRevision: HEAD
    path: argo-apps/django
  destination:
    server: https://kubernetes.default.svc
    namespace: django
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true