apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
  labels:
    app: django
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      serviceAccountName: django-service-account
      containers:
      - name: django
        image: django-app  # This will use the image defined in kustomization.yaml
        ports:
        - containerPort: 8000
        env:
          - name: DJANGO_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: django-secret
                key: secret_key
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: django-secret
                key: database_url