apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
  labels:
    app: django
spec:
  replicas: 2  # Scale up based on your load expectations
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: 350206045032.dkr.ecr.us-east-1.amazonaws.com/django-production:latest  # Replace with your ECR image path
        ports:
        - containerPort: 8000  # Match the port exposed in your Dockerfile
        env:
          - name: DJANGO_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: django-secret  # Ensure this secret is defined in your cluster
                key: secret_key
          - name: ALLOWED_HOSTS
            value: '*'  # Allows all hosts, adjust if necessary for production
      serviceAccountName: django  # Assuming IRSA setup for permissions
