apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
  labels:
    app: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
        - name: django
          image: 350206045032.dkr.ecr.us-east-1.amazonaws.com/django-production:latest
          ports:
            - containerPort: 8000
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: "myproject.settings"
            - name: DJANGO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: django-secrets
                  key: DJANGO_SECRET_KEY
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: django-secrets
                  key: RDS_DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: django-secrets
                  key: RDS_DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: django-secrets
                  key: RDS_DB_PASSWORD
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: django-secrets
                  key: RDS_DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: django-secrets
                  key: RDS_DB_PORT
          volumeMounts:
            - name: static-files
              mountPath: /app/static
            - name: media-files
              mountPath: /app/media
      volumes:
        - name: static-files
          persistentVolumeClaim:
            claimName: django-static-pvc
        - name: media-files
          persistentVolumeClaim:
            claimName: django-media-pvc