apiVersion: batch/v1
kind: Job
metadata:
  name: post-sync-annotations-job
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      serviceAccountName: django
      containers:
      - name: kubectl
        image: bitnami/kubectl:latest
        imagePullPolicy: IfNotPresent
        command: # 350206045032.dkr.ecr.us-east-1.amazonaws.com/django-production
          - /bin/sh
          - -c
          - |
            kubectl patch application "django" -n argocd --type=merge \
            -p '{"metadata":{"annotations":{"argocd-image-updater.argoproj.io/image-list":"${ARGOCD_AWS_ECR_REPO}/django-production"}}}'
      restartPolicy: Never

