apiVersion: batch/v1
kind: Job
metadata:
  name: restart-argo-cd-repo-server
  namespace: argocd
  annotations:
    argocd.argoproj.io/hook: PostSync  # PostSync #
    argocd.argoproj.io/hook-delete-policy: HookSucceeded  # This will clean up the Job after successful execution
    #argocd.argoproj.io/sync-wave: "1" #
spec:
  #backoffLimit: 2
  template:
    spec:
      serviceAccountName: argocd-image-updater
      containers:
      - name: kubectl-restart
        image: bitnami/kubectl:latest
        imagePullPolicy: IfNotPresent
        command: # kubectl annotate es django-secrets force-sync=$(date +%s) --overwrite -n django # kubectl annotate es jenkins-secrets force-sync=$(date +%s) --overwrite -n jenkins
        - /bin/sh
        - -c
        - |
          sleep 20;
          kubectl delete secretstore django-secrets -n django;
          kubectl delete externalsecret django-secrets -n django;;
      restartPolicy: Never