apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

#images:
#  - name: django-app-image
#    newName: 123456789012.dkr.ecr.us-east-1.amazonaws.com/my-django-app
#    newTag: "latest"  # pending. automate tag

# Use configMapGenerator or other generators if needed
configMapGenerator:
  - name: app-config
    literals:
      - placeholder=placeholder-value