apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: django # crucial for configMapGenerator
resources:
- deployment.yaml
- ingress.yaml
- pvc.yaml
- secrets.yaml
- service.yaml
- serviceaccount.yaml
#- job.yaml # hackish way to get around applicationset not supporting env substitution, using ignoreApplicationDifferences in the appset
- rbac.yaml
configMapGenerator:
- name: nginx-config
  files:
  - ../../django/nginx/default.conf # load the nginx default.conf from the django project directory
# the newName: def below has a seemingly hardcoded string, but is updated by image updater dynamically, since it has access to the repo. # pending
images: # argocd image-updater # required for argocd to sync
- name: django-production-kustomize
  newName: 350206045032.dkr.ecr.us-east-1.amazonaws.com/django-production
  newTag: c4cfc18db23d3d8effd30a3e26eb1b43a5071e8d
