apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: django # crucial for configMapGenerator

resources:
  - deployment.yaml
  - ingress.yaml
  - pvc.yaml
  - secrets.yaml
  - service.yaml
  - serviceaccount.yaml
  - application.yaml

configMapGenerator:
  - name: nginx-config
    files:
      - ../../django/nginx/default.conf # load the nginx default.conf from the django project directory

#patches:
#  - patch: |-
#      - op: add
#        path: /metadata/annotations/argocd-image-updater.argoproj.io~1image-list
#        value: "django=350206045032.dkr.ecr.us-east-1.amazonaws.com/django-production"
#      - op: add
#        path: /metadata/annotations/argocd-image-updater.argoproj.io~1django.update-strategy
#        value: "latest"
#      - op: add
#        path: /metadata/annotations/argocd-image-updater.argoproj.io~1django.allow-tags
#        value: "regexp:^.*"
#    target:
#      kind: ApplicationSet
#      apiVersion: argoproj.io/v1alpha1
#      name: django

#patches:
#  - patch: |-
#      - op: add
#        path: /metadata/annotations/argocd.argoproj.io~1compare-options
#        value: ServerSideDiff=true
#    target:
#      kind: Application
#      name: django # pending. make dynamic

#patches:
#  - patch: |-
#      - op: add
#        path: /metadata/annotations
#        value:
#          argocd-image-updater.argoproj.io/image-list: "django=350206045032.dkr.ecr.us-east-1.amazonaws.com/django-production"
#          argocd-image-updater.argoproj.io/django.update-strategy: "latest"
#          argocd-image-updater.argoproj.io/django.allow-tags: "regexp:^.*"

#patches:
#- path: imageupdater.yaml
#  target:
#    name: django
#    kind: Application
#    namespace: argocd
#  options:
#    allowNameChange: true
#    allowKindChange: true