apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: django # crucial for configMapGenerator

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - pvc.yaml
  - secrets.yaml
  - serviceaccount.yaml