apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: django # crucial for configMapGenerator
resources:
- deployment.yaml
- ingress.yaml
- pvc.yaml
- secrets.yaml
- service.yaml
- serviceaccount.yaml
- job.yaml # hackish way to get around applicationset not supporting env substitution, alongside ignoreApplicationDifferences in the appset
configMapGenerator:
- name: nginx-config
  files:
  - ../../django/nginx/default.conf # load the nginx default.conf from the django project directory
# ArgoCD Image Updater, creates/updates `.argocd-source-django.yaml` and uses that file to update the image according to update-strategy annotation
images: # argocd image-updater # required for argocd to sync
- name: django-production-kustomize
  newName: 350206045032.dkr.ecr.us-east-1.amazonaws.com/django-production
  newTag: 30b764558adfbd80f7cfbb1a5e4bd1869a4bea0f