apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-static-pvc
  labels:
    app: django
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-media-pvc
  labels:
    app: django
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi