apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: django-secrets
  namespace: django # match with app namespace
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: external-secrets # must match serviceAccount name (defined in ESO tf helm chart)
    kind: SecretStore
  target:
    name: django-ecr-url
    creationPolicy: Merge # Owner # Owner managed by ESO
  data:
    - secretKey: ecrUrl # arbitrary assigned key name, used in deployment.yaml
      remoteRef:
        key: ecr_repo  # The path to SSM parameter