apiVersion: v1
kind: ServiceAccount
metadata:
  name: django
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::350206045032:role/DjangoRole"
    #eks.amazonaws.com/role-arn: "arn:aws:iam::{AWS_ACCOUNT}:role/DjangoRole"