apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - rbac.yaml
#  - serviceaccount.yaml
  - secrets.yaml

helmCharts:
  - name: argocd-image-updater
    repo: https://argoproj.github.io/argo-helm
    version: 0.11.0 # Chart 0.11.0, App 0.14.0 #Chart 0.10.2, App v0.13.1
    releaseName: argocd-image-updater
    namespace: argocd
    includeCRDs: false
    valuesFile: values.yaml