apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
  namespace: argocd
data:
  kube.events: 'false'
  log.level: "trace"
  registries.conf: |
    registries:
      - api_url: https://350206045032.dkr.ecr.us-east-1.amazonaws.com
        credentials: ext:/scripts/ecr-login.sh
        credsexpire: 6h
        default: true
        insecure: false
        name: ECR
        ping: true
        prefix: 350206045032.dkr.ecr.us-east-1.amazonaws.com
        tagsortmode: none