apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: 'arn:aws:iam::${ARGOCD_AWS_ACCOUNT}:role/ImageUpdaterRole' # ${ARGOCD_AWS_ACCOUNT} # 350206045032
  name: argocd-image-updater
  namespace: argocd