nodeSelector:
  role: ci-cd

serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::350206045032:role/ArgoCDRole"

config:
  applicationsAPIKind: "kubernetes"
  registries:
    - api_url: https://350206045032.dkr.ecr.us-east-1.amazonaws.com
      prefix: 350206045032.dkr.ecr.us-east-1.amazonaws.com
      name: ECR
      ping: true
      insecure: false
      default: true
      credentials: ext:/scripts/ecr-login.sh
      credsexpire: 6h

authScripts:
  enabled: true
  scripts:
    ecr-login.sh: |
      #!/bin/sh
      # Retrieve the authorization token from AWS ECR
      auth_token=$(aws ecr get-authorization-token --region us-east-1 --output text --query 'authorizationData[].authorizationToken')
      
      # Decode the authorization token
      decoded_token=$(echo $auth_token | base64 -d)
      
      # Extract username and password
      username=$(echo $decoded_token | cut -d: -f1)
      password=$(echo $decoded_token | cut -d: -f2)
      
      # Output username and password
      echo "$username:$password"
    ecr-login2.sh: |
      #!/bin/sh
      aws ecr --region "us-east-1" get-authorization-token --output text --query 'authorizationData[].authorizationToken' | base64 -d