apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: django-secrets
  namespace: django
spec:
  provider:
    aws:
      service: ParameterStore # SystemManager
      region: us-east-1  # AWS region specific, pending dynamic value
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets # must match serviceAccount name (defined in ESO tf helm chart)
            namespace: kube-system # must match ESO namespace (defined in ESO tf helm chart)
