prometheus:
  prometheusSpec:
    retention: "10d"  # Retains metrics for 10 days
    resources:
      limits:
        cpu: "500m"
        memory: "1500Mi"
      requests:
        cpu: "200m"
        memory: "1000Mi"

alertmanager:
  config:
    global:
      resolve_timeout: "5m"
    route:
      group_by: ['job']
      group_wait: "30s"
      group_interval: "5m"
      repeat_interval: "12h"
      receiver: 'null'
    receivers:
      - name: 'null'

grafana:
  enabled: true
  adminPassword: "securepassword"
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "200m"
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
    hosts:
      - grafana.your-domain.com

# Node Exporter and Kube State Metrics resource limits
nodeExporter:
  enabled: true
  resources:
    limits:
      cpu: "100m"
      memory: "180Mi"
    requests:
      cpu: "50m"
      memory: "120Mi"

kubeStateMetrics:
  enabled: true
  resources:
    limits:
      cpu: "100m"
      memory: "150Mi"
    requests:
      cpu: "50m"
      memory: "100Mi"