apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/tbalza/kubernetes-cicd.git
      revision: HEAD
      directories:
      - path: argo-apps-kustomize/*
  template:
    metadata:
      name: '{{.path.basename}}'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/tbalza/kubernetes-cicd.git
        targetRevision: HEAD
        path: '{{.path.path}}'
        # kustomize: {} commonAnnotations can be used to pass build numbers to kustomize
      destination:
        server: https://kubernetes.default.svc # pending make dynamic from repo files
        namespace: '{{.path.basename}}' # pending make dynamic from repo files
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true