apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: unified-apps
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: "https://github.com/tbalza/kubernetes-cicd.git"
      revision: HEAD
      files:
        - path: "argo-apps/**/config.yaml" # dynamically derived from the basename of the path where config.yaml is found
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: '{{helmchart_url}}'
        targetRevision: '{{version}}'
        chart: '{{chart}}'
        helm:
          valueFiles:
            - "{{path.dirname}}/values-override.yaml" # values-override.yaml relative to the directory containing config.yaml
      destination:
        server: '{{cluster_server}}'
        namespace: '{{app_namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
