apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  kustomize.buildOptions: "--enable-helm --load_restrictor none" # "--enable-helm"

# setting this through helm override crashed argocd for some reason