## Service account not currently able to be defined with envsubst plugin
## Instead the annotation is bootsrapped in tf with helm resource
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::${ARGOCD_AWS_ACCOUNT}:role/ArgoCDrepoRole"
  name: argo-cd-argocd-repo-server