apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/tbalza/kubernetes-cicd.git
      revision: HEAD
      directories:
      - path: argo-apps/* # add an exclude for django, create Application.yaml separately ?
  template:
    metadata:
      name: '{{.path.basename}}'
      annotations: {}
#        argocd-image-updater.argoproj.io/app.update-strategy: latest
    spec:
      project: "default" # check
      source:
        repoURL: https://github.com/tbalza/kubernetes-cicd.git # check
        targetRevision: HEAD # check
        path: '{{.path.path}}'
        kustomize:
          patches:
            - target:
                kind: ApplicationSet
                name: '{{.path.basename}}'
              patch: |-
                - op: add
                  path: /metadata/annotations/argocd-image-updater.argoproj.io~1image-list
                  value: '{{.path.basename}}=350206045032.dkr.ecr.us-east-1.amazonaws.com/{{.path.basename}}-production'
                - op: add
                  path: /metadata/annotations/argocd-image-updater.argoproj.io~1{{.path.basename}}.update-strategy
                  value: 'latest'
                - op: add
                  path: /metadata/annotations/argocd-image-updater.argoproj.io~1{{.path.basename}}.allow-tags
                  value: 'regexp:^.*'
#        kustomize:
#          commonAnnotations:
#            app.kubernetes.io/managed-by: argocd # delete-hook test
      destination:
        server: https://kubernetes.default.svc # pending make dynamic from repo files
        namespace: '{{.path.basename}}' # pending make dynamic from repo files
      syncPolicy:
        automated:
          selfHeal: true
          prune: true  # Enables the deletion of resources that are no longer in source
        syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true