apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/tbalza/kubernetes-cicd.git
      revision: HEAD
      directories:
      - path: argo-apps/* # add an exclude for django, create Application.yaml separately ?
  template:
    metadata:
      name: '{{.path.basename}}'
      annotations: # image list has `app name` prepended before an `=` (django) and the ecr repo. corresponding annotations are prepended with the same app name (django.xxx)
        argocd-image-updater.argoproj.io/image-list: "django=350206045032.dkr.ecr.us-east-1.amazonaws.com/django-production"
        argocd-image-updater.argoproj.io/django.update-strategy: "newest-build" # digest # "newest-build"
        argocd-image-updater.argoproj.io/django.kustomize.image-name: "350206045032.dkr.ecr.us-east-1.amazonaws.com/django-production"
        argocd-image-updater.argoproj.io/write-back-method: argocd # `argocd`/`git`
        #argocd-image-updater.argoproj.io/git-branch: main # important for git writeback
        #argocd-image-updater.argoproj.io/django.force-update: "true"
        #argocd-image-updater.argoproj.io/django.allow-tags: any
        #argocd-image-updater.argoproj.io/django.ignore-tags: latest, master
        #argocd-image-updater.argoproj.io/django.allow-tags: "regexp:^.*"
    spec:
      project: "default" # check
      source:
        repoURL: https://github.com/tbalza/kubernetes-cicd.git # check
        targetRevision: HEAD # check
        path: '{{.path.path}}'
#        kustomize:
#          commonAnnotations:
#            app.kubernetes.io/managed-by: argocd # delete-hook test
      destination:
        server: https://kubernetes.default.svc # pending make dynamic from repo files
        namespace: '{{.path.basename}}' # pending make dynamic from repo files
      syncPolicy:
        automated:
          selfHeal: true
          prune: true  # Enables the deletion of resources that are no longer in source
        syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true