apiVersion: v1
items:
- apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    creationTimestamp: "2024-06-07T20:41:26Z"
    generation: 1
    labels:
      app.kubernetes.io/component: server
      app.kubernetes.io/instance: argo-cd
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: argocd-server
      app.kubernetes.io/part-of: argocd
      app.kubernetes.io/version: v2.10.7
      argocd.argoproj.io/instance: argocd
      helm.sh/chart: argo-cd-6.7.14
    name: argo-cd-argocd-server
    namespace: argocd
    resourceVersion: "57217"
    uid: bafa820e-e1eb-4534-a0f6-bd68219616c9
  spec:
    rules:
    - host: argocd.tbalza.net
      http:
        paths:
        - backend:
            service:
              name: argo-cd-argocd-server
              port:
                number: 80
          path: /
          pathType: Prefix
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""