apiVersion: batch/v1
kind: Job
metadata:
  name: restart-argo-cd-repo-server
  namespace: argocd
  annotations:
    argocd.argoproj.io/hook: Sync  # PostSync #
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      serviceAccountName: argocd-application-controller
      containers:
      - name: kubectl-restart
        image: bitnami/kubectl:latest
        imagePullPolicy: IfNotPresent
        command:
        - /bin/sh
        - -c
        - |
          kubectl rollout restart deployment argo-cd-argocd-repo-server -n argocd;
          kubectl rollout restart deployment argo-cd-argocd-redis -n argocd
      restartPolicy: Never