apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: argo-cd
    repo: https://argoproj.github.io/argo-helm
    version: 7.3.4 # Chart 7.3.4
    releaseName: argo-cd
    namespace: argocd
    includeCRDs: true # check if necessary ( as it should be defined in values.yaml)
    valuesFile: values.yaml
    valuesMerge: replace # specifies how to treat valuesInline with respect to Values. Legal values: ‘merge’, ‘override’, ‘replace’. Defaults to ‘override’. # check

resources:
  - ingress.yaml
  - secrets.yaml
  - image-updater/


