apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: argo-cd
    repo: https://argoproj.github.io/argo-helm
    version: 6.7.14 # Chart 6.7.14, app v v2.10.7
    releaseName: argo-cd
    namespace: argocd
    includeCRDs: true # check if necessary ( as it should be defined in values.yaml)
    valuesFile: values.yaml
#    valuesInline:
#      serviceAccount:
#        annotations:
#          eks.amazonaws.com/role-arn: $(ARGOCD_ROLE_ARN)

resources:
  - applicationset.yaml

#vars:
#  - name: ARGOCD_ROLE_ARN
#    objref:
#      kind: Secret
#      name: argocd-service-account-annotations
#      apiVersion: v1
#    fieldref:
#      fieldpath: data.role-arn

