apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: argo-cd
    repo: https://argoproj.github.io/argo-helm
    version: 7.3.4 # Chart 7.3.4
    releaseName: argo-cd
    namespace: argocd
    includeCRDs: true # check if necessary ( as it should be defined in values.yaml)
    valuesFile: values.yaml
    valuesMerge: replace # specifies how to treat valuesInline with respect to Values. Legal values: ‘merge’, ‘override’, ‘replace’. Defaults to ‘override’. # check
#    valuesInline:
#      serviceAccount:
#        annotations:
#          eks.amazonaws.com/role-arn: $(ARGOCD_ROLE_ARN)

resources:
  - ingress.yaml
  - secrets.yaml
  - secrets2.yaml
  - image-updater/
#  - deployment.yaml

#  - cmp.yaml
#  - application.yaml
#  - delete-hook.yaml
#  - applicationset.yaml

#vars:
#  - name: ARGOCD_ROLE_ARN
#    objref:
#      kind: Secret
#      name: argocd-service-account-annotations
#      apiVersion: v1
#    fieldref:
#      fieldpath: data.role-arn

