apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-controller-all-access
rules:
- apiGroups: ["*"]  # Allows access to all API groups
  resources: ["*"]  # Allows access to all resources
  verbs: ["*"]      # Allows all actions

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-controller-all-access-binding
subjects:
- kind: ServiceAccount
  name: argocd-application-controller
  namespace: argocd
roleRef:
  kind: ClusterRole
  name: argocd-controller-all-access
  apiGroup: rbac.authorization.k8s.io