apiVersion: batch/v1
kind: Job
metadata:
  name: restart-argo-cd-repo-server
  namespace: argocd
  annotations:
    argocd.argoproj.io/hook: PostSync  # This specifies that the Job is a post-sync hook
    argocd.argoproj.io/hook-delete-policy: HookSucceeded  # This will clean up the Job after successful execution
spec:
  backoffLimit: 2
  template:
    spec:
      serviceAccountName: argo-cd-argocd-repo-server
      containers:
      - name: kubectl-restart
        image: bitnami/kubectl:latest
        imagePullPolicy: IfNotPresent
        command:
        - /bin/sh
        - -c
        - kubectl rollout restart deployment argo-cd-argocd-repo-server -n argocd
      restartPolicy: Never