apiVersion: batch/v1
kind: Job
metadata:
  generateName: restart-repo-server-
  namespace: argocd
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "2"
spec:
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: argo-cd-argocd-repo-server
      containers:
      - name: restart
        image: bitnami/kubectl
        command:
        - /bin/sh
        - -c
        - |
          # Restart the deployment, this command runs once per deployment update
          kubectl rollout restart deployment argo-cd-argocd-repo-server -n argocd