apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-secrets-global
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"  # Applied first
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: argocd-secrets-global # must match `SecretStore` name
    kind: SecretStore
  target:
    name: argocd-secrets-global
    creationPolicy: Owner # Owner # Owner managed by ESO # Merge
    immutable: true # check
  data:
    - secretKey: ARGOCD_AWS_ACCOUNT # arbitrary assigned key name, used in deployment/application/appset.yaml
      remoteRef:
        key: argo_cd_aws_account_number  # The path to SSM parameter ### image updater
        conversionStrategy: Default # argocd appset will loop infinitely if not set
        decodingStrategy: None # argocd appset will loop infinitely if not set
        metadataPolicy: None # argocd appset will loop infinitely if not set
    - secretKey: ARGOCD_AWS_CLUSTER_NAME # arbitrary assigned key name, used in deployment/application/appset.yaml
      remoteRef:
        key: argo_cd_aws_cluster_name  # The path to SSM parameter ### image updater
        conversionStrategy: Default # argocd appset will loop infinitely if not set
        decodingStrategy: None # argocd appset will loop infinitely if not set
        metadataPolicy: None # argocd appset will loop infinitely if not set
    - secretKey: ARGOCD_AWS_ECR_REPO # arbitrary assigned key name, used in deployment/application/appset.yaml
      remoteRef:
        key: argo_cd_aws_ecr_repo  # The path to SSM parameter ### image updater
        conversionStrategy: Default # argocd appset will loop infinitely if not set
        decodingStrategy: None # argocd appset will loop infinitely if not set
        metadataPolicy: None # argocd appset will loop infinitely if not set
    - secretKey: ARGOCD_AWS_REGION # arbitrary assigned key name, used in deployment/application/appset.yaml
      remoteRef:
        key: argo_cd_aws_region  # The path to SSM parameter ### image updater
        conversionStrategy: Default # argocd appset will loop infinitely if not set
        decodingStrategy: None # argocd appset will loop infinitely if not set
        metadataPolicy: None # argocd appset will loop infinitely if not set
    - secretKey: ARGOCD_APP_DOMAIN # arbitrary assigned key name, used in deployment/application/appset.yaml
      remoteRef:
        key: argo_cd_aws_domain  # The path to SSM parameter ### image updater
        conversionStrategy: Default # argocd appset will loop infinitely if not set
        decodingStrategy: None # argocd appset will loop infinitely if not set
        metadataPolicy: None # argocd appset will loop infinitely if not set
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: argocd-secrets-global
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"  # Applied first
spec:
  provider:
    aws:
      service: ParameterStore
      region: us-east-1  # AWS region specific, pending dynamic value
      auth:
        jwt: # requires `sts:AssumeRoleWithWebIdentity` permission (set in tf)
          serviceAccountRef:
            name: argo-cd-argocd-repo-server # name of actual serviceAccount (not role) attached to IRSA
            # check which serviceAccount makes the most sense