serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::350206045032:role/ArgoCDRole"
# init containers or sidecars that configure or bootstrap the main containers based on dynamic inputs from secrets.

crds:
  keep: true # check # Keep CRDs on chart uninstall

global:
  domain: "argocd.tbalza.net" # Used for ingresses, certificates, SSO, notifications, etc. (blank allows all domains)

configs:
  cm:
    kustomize.buildOptions: "--load-restrictor LoadRestrictionsNone --enable-helm" # Enable Kustomize to install helm charts
  params:
    server.insecure: true # necessary when SSL termination is handled by ALB

server:
  service:
    type: ClusterIP
#  containerPorts:
#    server: 8282
#  extraArgs:
#    - --insecure
#  extraEnv:
#    - name: ARGOCD_INSECURE
#      value: "true"
  ingress:
    enabled: true # true
    controller: aws # Specifies that this is managed by AWS ALB
    aws:
      serviceType: ClusterIP # <- Used with target-type: ip
      backendProtocolVersion: GRPC
    ingressClassName: "alb" # (default `alb`) `alb-https` IngressClassParams set in tf container ACM ARN
    annotations:
      kubernetes.io/ingress.class: "alb" # (default `alb`) `alb-https` IngressClassParams set in tf container ACM ARN
      alb.ingress.kubernetes.io/scheme: "internet-facing" # change to "internal" when made private
      alb.ingress.kubernetes.io/backend-protocol: "HTTP" # traffic between the ALB and the pods is over HTTP
      alb.ingress.kubernetes.io/target-type: "ip" # check. target-type:instance/nodeport. NodePort range (30000-32767)
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]' # '[{"HTTP": 80}]'
      alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
      alb.ingress.kubernetes.io/group.name: "argo-cd-cluster"
      alb.ingress.kubernetes.io/group.order: "1"
      alb.ingress.kubernetes.io/healthcheck-path: "/healthz"
      alb.ingress.kubernetes.io/healthcheck-port: "traffic-port" # check
      alb.ingress.kubernetes.io/success-codes: "200,307" # check # 200
      #cert-manager.io/cluster-issuer: letsencrypt-prod-django # The name of the ClusterIssuer
      external-dns.alpha.kubernetes.io/hostname: argocd.tbalza.net
      ##external-dns.alpha.kubernetes.io/ingress-hostname-source: annotation-only # external-dns controller only creates DNS records for /hostname
      alb.ingress.kubernetes.io/certificate-arn: " arn:aws:acm:us-east-1:350206045032:certificate/47561cda-e12f-48cd-a4c5-29a1ca67fcd0"

#    tls: true
    tls: # TLS configuration block
      - hosts:
          - argocd.tbalza.net
    path: "/" # /
    pathType: "Prefix" #"ImplementationSpecific"
    hostname: "argocd.tbalza.net" # references global: for domain

applicationSet:
  enabled: true
  nodeSelector:
    role: ci-cd

dex:
  enabled: false # This is for SSO
  server:
    nodeSelector:
      role: ci-cd

notifications:
  controller:
    nodeSelector:
      role: ci-cd

controller:
  nodeSelector:
    role: ci-cd

repoServer:
  nodeSelector:
    role: ci-cd
