serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::350206045032:role/ArgoCDRole"

server:
  service:
    type: ClusterIP
  containerPorts:
    server: 8282
  extraArgs:
    - --insecure
  extraEnv:
    - name: ARGOCD_INSECURE
      value: "true"

applicationSet:
  enabled: true
  nodeSelector:
    role: ci-cd

dex:
  server:
    nodeSelector:
      role: ci-cd

notifications:
  controller:
    nodeSelector:
      role: ci-cd

controller:
  nodeSelector:
    role: ci-cd

repoServer:
  nodeSelector:
    role: ci-cd

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "alb"
    alb.ingress.kubernetes.io/scheme: "internet-facing"
    alb.ingress.kubernetes.io/target-type: "ip"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'  # Adjust as necessary for HTTPS
    alb.ingress.kubernetes.io/healthcheck-path: "/healthz"
    alb.ingress.kubernetes.io/group.name: "argo-cd-cluster"
    alb.ingress.kubernetes.io/group.order: "1"
  paths:
    - path: "/*"
      pathType: "ImplementationSpecific"
  hosts:
    - "*"  # Adjust if you have specific domain
  serviceName: "argo-cd-argocd-server"
  servicePort: 80
