apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: prometheus
    repo: git@github.com:prometheus-community/helm-charts.git # https://github.com/prometheus-community/helm-charts
    version: 58.5.3
    releaseName: kube-prometheus-stack
    namespace: prometheus
    includeCRDs: true # check if necessary ( as it should be defined in values.yaml)
    valuesFile: values.yaml